# Generated by Django 3.2.6 on 2021-09-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210915_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitees',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
