# Generated by Django 3.2.6 on 2021-09-20 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_auto_20210920_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invitee', to=settings.AUTH_USER_MODEL),
        ),
    ]
